source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.0.0'

# Use sqlite3 as the database for Active Record
gem 'sqlite3'

# Use SCSS for stylesheets
gem 'sass-rails', '~> 4.0.0.rc1'

# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'

# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '~> 4.0.0'

# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'

# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 1.0.1'

# generate UUIDs
gem 'uuidtools'

# scrape html
gem 'nokogiri'

# authentication
gem 'browserid-rails', git: 'git://github.com/dbp/browserid-rails.git', ref: 'a3cbb2bb60a23be717b4f206c9afe75341911edb'

group :doc do
  # bundle exec rake doc:rails generates the API under doc/api.
  gem 'sdoc', require: false
end

group :development, :test do
  gem 'rspec-rails', '~> 2.0'
  gem 'jasmine-rails'
#  gem 'guard-jasmine'
end

# NOTE(joe); the ref below is from branch 'development' on 10 Jun 2013
gem 'rugged', git: 'git://github.com/libgit2/rugged.git', ref: '35ebf0f1e56883dfbc5775fce163d2d8fa259ae6', submodules: true

group :development do
  gem 'guard-rails'
  gem 'guard-rspec'
end

group :production do
  gem 'pg'
end

# Use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# Use unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano', group: :development

# Use debugger
# gem 'debugger', group: [:development, :test]
